name: Build and package
on:
  pull_request:
    types: [ready_for_review]
  workflow_dispatch:
    
jobs:
  vagrant-up:
    runs-on: macos-10.15

    strategy:
      fail-fast: true
      matrix:
        provider: [virtualbox] # Add libvirt once available

    name: Build Vagrant Box for ${{ matrix.provider }}

    steps:
    - uses: actions/checkout@v2
      with:
        lfs: true

    - name: Cache Vagrant boxes
      uses: actions/cache@v2
      with:
        path: ~/.vagrant.d/boxes
        key: ${{ runner.os }}-vagrant-${{ hashFiles('Vagrantfile') }}
        restore-keys: |
          ${{ runner.os }}-vagrant-

    - name: Install libvirt
      if: matrix.provider == 'libvirt'
      run: |
        # Install libvirt etc
        echo "libvirt is currently not supported"
        exit 1
        # Install vagrant plugin
        # vagrant plugin install vagrant-libvirt

    - name: Show Vagrant version
      run: vagrant --version

    - name: Run vagrant up
      run: |
        vagrant up --provider=${{ matrix.provider }}

    - name: Package Vagrant box
      run: vagrant package --base "preCICE-VM" --output preCICE.box

    - name: Generate Vagrant box SHA256 hash
      run: shasum -a 256 preCICE.box

    - name: Upload artifacts
      uses: actions/upload-artifact@v2
      with:
          name: precice-vagrant-box-${{ matrix.provider }}
          path: preCICE.box
          retention-days: 7
        
